# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Archive
tagline:          from junior BE Developer
description:      "The Archive from junior Back-end Developer @codepark"
url:              https://codepark.kr
baseurl:          /
                  # the optional subpath of your site, e.g. "/my-jekyll-site/"
                  # This will apply to all pages in your Jekyll site.

author:
  name:           codepark
  url:            https://twitter.com/karloespiritu

paginate:         5
paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars
version:            2.0.1

github:
  repo:             https://codepark-kr.github.io
