title: 'b2a3e8.github.io'
description: "A jekyll theme inspired by linux consoles for hackers, developers and script kiddies."
baseurl: "/"
url: "https://b2a3e8.github.io"

header_pages:
  - index.md
  - spring-theory.md
  - about.md
  - contact.md

style: dark

gems:
  - jekyll-seo-tag

footer: 'copyright ©codepark.kr@gmail.com'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
